### ISSUE TITLE
A bug and memory leak!

### ISSUE THREAD

**Issue by digweedro** [shin10/Starling-FFParticleSystem#11]
I have finished experimenting with FFParticle stress tests and although the performance is amazing I had an issue tracking down a memory leak which ended in FFParticleSystem.
In my current setup I relying on "FFParticleSystem.init(1024, false, 512, 8);" and "FFParticleSystem.dispose();" (resetting the particle system with different configurations for the current scene state). During a scene lifetime I spawn particle systems ( alot of them ). When "FFParticleSystem.dispose()" is called I noticed memory not being released. The static function "dispose()" calls internally for "disposePool()" which looks like this:

public static function disposePool():void
{
	for each (var instance:FFParticleSystem in sInstances)
	{
		instance.dispose();
	}
 
	sParticlePool = null;
}

Following down the "instance.dispose()" method leads to this:

public override function dispose():void
{
	sInstances.splice(sInstances.indexOf(this), 1); // <= modifies the length
	removeEventListener(starling.events.Event.ADDED_TO_STAGE, addedToStageHandler);
	stop(true);
	mBatched = false;
	super.filter = mFilter = null;
	removeFromParent();
 
	super.dispose();
	mDisposed = true;
}

You call "sInstances.splice(sInstances.indexOf(this), 1);" which modifies the vector length and messes up the previous loop "for each (var instance:FFParticleSystem in sInstances)" resulting in a number of skipped instances not getting disposed. The quick fix I did was this:

for (var i : int=sInstances.length-1; i>=0; i--)
{
	sInstances[i].dispose();
}

This bug does not lead to a memory leak but it can lead to a runtime error when after calling:
FFParticleSystem.dispose(), a "skipped from being disposed" ParticleSystem may be left on stage or inside a starling sprite and if you call dispose() on that sprite container it will iterate trough all children and call dispose on them. Call will brake when a particle system is encountered.

**Comment by digweedro** [comment]
Also I have a found a small memory leak ( but only combined with bad practice from developer :P ). If you instantiate a couple of particle systems and place them on stage and call repeatedly on them myPs.stop(true) and myPs.start() will slowly increase memory without ever disposing it. ( "stop" must be called with the "clear parameter.

I also feel I need to say SUPERB WORK! with the extension. The performance i got on mobile (specially low end ones) is amazing.

**Comment by shin10** [comment]
Hi there,

sorry for the late reply and thanks for the kind words. I just replaced the for each loops like you suggested. Actually I can't beliefe I used them. ^^

About your second issue. I can't replicate that. Maybe it's a missunderstanding. pause()/resume() toggles the animation, while start() and stop() are used to change the emitting state but won't stop the animation (for example ... a flamethrower?). So it depends on what you actually want to do. If you want to get rid of the system instance, dispose() should be the best choice. If you want to instantly remove the instance, but keep it for later reuse, I'd also suggest to use stop(true).

Kind regards

Michael

**Comment by digweedro** [comment]
No problem Michael! Thanks for fixing this up :D. 
About the second issue: I was actually using it correctly as you mentioned. Needed start() stop() for a ship engine thrust which is basically a flamethrower and also I was calling stop( true ) to dispose for later usage ( pooling the systems ). Weird is I can't reproduce it either but I updated my code a lot so it may be possible it was something on my end :P.

**Comment by shin10** [comment]
Great. :D
Let me know, when you're done and where I can check it out. :)
