### ISSUE TITLE
rotation in texture atlas causes particles to be scaled incorrectly

### ISSUE THREAD

**Issue by YAYitsAndrew** [shin10/Starling-FFParticleSystem#13]
I have a particle that is longer than it is tall.  The image file itself is 64x64 but when I set Texture Packer to trim whitespace it ends up as 64x25.  I've also allowed rotations in Texture Packer.  The combination of these two things seems to confuse FFParticleSystem about which dimension is the height and the width.  So it mistakes the 25 for the width and scales up the particles accordingly (64/25 = 256% scale).

I can work around this issue by disallowing rotation in my texture atlas

![Example Particle](http://i.imgur.com/EvubUzY.png)

**Comment by shin10** [comment]
Hi Andrew,

I'm not sure that it's working now, since I don't have TexturePacker but I hope so. Just let me know.

**Comment by YAYitsAndrew** [comment]
Thanks for taking a look, unfortunately the bug is still there.  Here's what I see when the pfx is rotated in the atlas:

![Rotation allowed](http://i.imgur.com/FPTgGvh.png)

Here it is if I disable atlas rotation:

![Rotation not allowed](http://i.imgur.com/jC4TyKH.png)

And here's a shot of the pfx in TexturePacker when it doesn't work.
![TexturePacker](http://i.imgur.com/PQSre1d.png)

I'll take a look at your change and see if I can figure out a solution

**Comment by YAYitsAndrew** [comment]
I think I found a good area to finish your fix.  In FFParticleSystem.initParticle() around line 979 is this:

```javascript
var firstFrameWidth:Number = mFrameLUT[0].particleHalfWidth << 1;
particle.scale = startSize / firstFrameWidth;
```

I think this code should check the rotation property of the Frame instance and use height instead of width to set firstFrameWidth.  I did a test and it seemed to work but I'll leave it to you to finalize the implementation.

```javascript
var firstFrameWidth:Number = (mFrameLUT[0].rotated ? mFrameLUT[0].particleHalfHeight : mFrameLUT[0].particleHalfWidth) << 1;
particle.scale = startSize / firstFrameWidth;
```

**Comment by shin10** [comment]
Ah, so it was "just" the scale of the particle, and not resulting in any distortion. My bad.

Thanks

**Comment by YAYitsAndrew** [comment]
It works! Thank you!
